
#include "test_functions.h"

int main ()try {
    aufgabe3();
}
catch(...) {
    cout << "unknown error" << endl;
}

